# Generated by Django 3.1.7 on 2021-03-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shade',
            name='image',
        ),
        migrations.RemoveField(
            model_name='shade',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='skuimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='skuimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='modelwithimage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл изображения'),
        ),
        migrations.AddField(
            model_name='modelwithimage',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на изображение'),
        ),
    ]
