# Generated by Django 3.1.7 on 2021-03-31 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210331_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('modelwithimage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.modelwithimage')),
                ('title', models.CharField(max_length=1023, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            bases=('app.modelwithimage',),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1023, verbose_name='Заголовок')),
                ('author', models.CharField(max_length=1023, verbose_name='Автор')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('date', models.DateField(verbose_name='Дата')),
                ('pros', models.TextField(verbose_name='Плюсы')),
                ('cons', models.TextField(verbose_name='Минусы')),
            ],
        ),
        migrations.CreateModel(
            name='AboutArticle',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.article')),
            ],
            bases=('app.article',),
        ),
        migrations.CreateModel(
            name='AdviseArticle',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.article')),
            ],
            bases=('app.article',),
        ),
    ]
